## **Numpy 的使用**
### **匯入 Numpy**
通常會使用 `import numpy as np` 來將 Numpy 匯入，並將其簡稱為 `np`

In [1]:
import numpy as np

### **建立一個 Array (陣列)**

In [6]:
# range from 0 to 10
z = np.arange(10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


### **查看變數或Array的維度 (dimension)**
Numpy的陣列擁有一個屬性稱作 `shape`，可以查看其維度與大小。

In [9]:
print('{:<15}'.format('data type:'), end='')
print(type(z))

print('{:<15}'.format('data shape:'), end='')
print(z.shape)

data type:     <class 'numpy.ndarray'>
data shape:    (10,)


### **擴充 Array 的維度**
- 使用 Numpy Array 的 `expand_dims()` method 來擴充維度。
- `axis` parameter 用來指定要插入的新維度在哪裡，index 從 0 開始算。

In [12]:
# 當矩陣要進行相加或相乘時可能會用到
np.expand_dims(z, axis = -1).shape

(10, 1)

In [19]:
# 在後面 INDEX=-1 和前面 INDEX=0 插入新維度
z1 = np.expand_dims( np.expand_dims(z, axis = -1) , axis = 0)

print('{:<20}'.format('data type (z1):'), end='')
print(type(z1))
print('{:<20}'.format('data shape (z1):'), end='')
print(z1.shape)

data type (z1):     <class 'numpy.ndarray'>
data shape (z1):    (1, 10, 1)


### **刪除 Array 的維度**
- 使用 Numpy Array 的 `squeeze()` method 來擴充維度。
- `axis` parameter 用來指定所要刪除的維度，index 從 0 開始算。

In [20]:
np.squeeze(z1, axis = -1).shape

(1, 10)

### **根據既有 Array 來重新塑造形狀**
- 使用 Numpy Array 的 `reshape()` method 來擴充維度。

In [27]:
# 重新塑形
z2 = z.reshape((2, 5))

z2


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [28]:
print('{:<20}'.format('data type (z2):'), end='')
print(type(z2))
print('{:<20}'.format('data shape (z2):'), end='')
print(z2.shape)

data type (z2):     <class 'numpy.ndarray'>
data shape (z2):    (2, 5)


### **堆疊 Array** (Stacking)
- `hstack` 是指 horizontal stack，橫向堆疊。
- `vstack` 是指 vertical stack，縱向堆疊。

In [29]:
np.hstack((z2, z2))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [30]:
np.vstack((z2, z2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### **max()**

In [31]:
np.max(z2, axis = 1)

array([4, 9])

### **argmax()**
- argument maximum

In [32]:
np.argmax(z2, axis = 1)

array([4, 4], dtype=int64)

### **轉置 Array** (轉置矩陣)
- 透過呼叫 Numpy Array 的 `.T` 屬性來取得轉置矩陣

In [34]:
z2.T # 轉置矩陣

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### **Array 的乘法**
- 使用 `*` method 來進行。

In [41]:
a = z2[0, :]    # 取 z2 的第一個維度的第 0 組資料
b = z2[1, :]    # 取 z2 的第一個維度的第 1 組資料
print(a)
print('{:<20}'.format('data shape (a):'), end='')
print(a.shape)

print('-------------------------------')
print(b)
print('{:<20}'.format('data shape (b):'), end='')
print(b.shape)

print('-------------------------------')
print(a * b)
print('{:<20}'.format('data shape (a*b):'), end='')
print((a*b).shape)
# a.dot(b)

[0 1 2 3 4]
data shape (a):     (5,)
-------------------------------
[5 6 7 8 9]
data shape (b):     (5,)
-------------------------------
[ 0  6 14 24 36]
data shape (a*b):   (5,)
