## **Numpy 的使用**
### **匯入 Numpy**
通常會使用 `import numpy as np` 來將 Numpy 匯入，並將其簡稱為 `np`

In [3]:
import numpy as np

### **建立一個 Array (陣列)**

In [4]:
# range from 0 to 9
z = np.arange(10)
print(z)

[0 1 2 3 4 5 6 7 8 9]


### **查看變數或Array的維度 (dimension)**
Numpy的陣列擁有一個屬性稱作 `shape`，可以查看其維度與大小。

In [5]:
print('{:<15}'.format('data type:'), end='')
print(type(z))

print('{:<15}'.format('data shape:'), end='')
print(z.shape)

data type:     <class 'numpy.ndarray'>
data shape:    (10,)


### **擴充 Array 的維度**
- 使用 Numpy Array 的 `expand_dims()` method 來擴充維度。
- `axis` parameter 用來指定要插入的新維度在哪裡，index 從 0 開始算。

In [6]:
# 當矩陣要進行相加或相乘時可能會用到
np.expand_dims(z, axis = -1).shape

(10, 1)

In [7]:
# 在後面 INDEX=-1 和前面 INDEX=0 插入新維度
z1 = np.expand_dims( np.expand_dims(z, axis = -1) , axis = 0)

print('{:<20}'.format('data type (z1):'), end='')
print(type(z1))
print('{:<20}'.format('data shape (z1):'), end='')
print(z1.shape)

data type (z1):     <class 'numpy.ndarray'>
data shape (z1):    (1, 10, 1)


### **刪除 Array 的維度**
- 使用 Numpy Array 的 `squeeze()` method 來擴充維度。
- `axis` parameter 用來指定所要刪除的維度，index 從 0 開始算。

In [8]:
np.squeeze(z1, axis = -1).shape

(1, 10)

### **根據既有 Array 來重新塑造形狀**
- 使用 Numpy Array 的 `reshape()` method 來擴充維度。

In [9]:
# 重新塑形
z2 = z.reshape((2, 5))

z2


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [10]:
print('{:<20}'.format('data type (z2):'), end='')
print(type(z2))
print('{:<20}'.format('data shape (z2):'), end='')
print(z2.shape)

data type (z2):     <class 'numpy.ndarray'>
data shape (z2):    (2, 5)


### **堆疊 Array** (Stacking)
- `hstack` 是指 horizontal stack，橫向堆疊。
- `vstack` 是指 vertical stack，縱向堆疊。

In [11]:
np.hstack((z2, z2))

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

In [12]:
np.vstack((z2, z2))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### **尋找最大值**
- 尋找矩陣中的最大值，可以使用 `.max()` 這個 method。
  - `axis` 用來設定在哪個軸上進行搜索
    - `axis=None` 或是不輸入 `axis`，表示找的是整個矩陣中的最大值。（預設）
    - `axis=0` 表示在欄位 (垂直位) 上操作，返回每欄的最大值。
    - `axis=1` 表示在列 (水平位) 上操作，返回每列的最大值。
- 尋找矩陣中最大值的位置，可以使用 `.argmax()` 這個 method。
  - 細項同 `.max()`。

In [28]:
arr = np.array([[1, 2, 9],
                [4, 8, 6],
                [7, 5, 3]])

# 找出最大值
print('{:<25} ='.format('np.max(arr)'), np.max(arr))
print('{:<25} ='.format('np.max(arr, axis=None)'), np.max(arr, axis=None))
print('{:<25} ='.format('np.max(arr, axis=0)'), np.max(arr, axis=0))
print('{:<25} ='.format('np.max(arr, axis=1)'), np.max(arr, axis=1))

# 找出最大值位置
print('{:<25} ='.format('np.argmax(arr)'), np.argmax(arr))
print('{:<25} ='.format('np.argmax(arr, axis=None)'), np.argmax(arr, axis=None))
print('{:<25} ='.format('np.argmax(arr, axis=0)'), np.argmax(arr, axis=0))
print('{:<25} ='.format('np.argmax(arr, axis=1)'), np.argmax(arr, axis=1))

np.max(arr)               = 9
np.max(arr, axis=None)    = 9
np.max(arr, axis=0)       = [7 8 9]
np.max(arr, axis=1)       = [9 8 7]
np.argmax(arr)            = 2
np.argmax(arr, axis=None) = 2
np.argmax(arr, axis=0)    = [2 1 0]
np.argmax(arr, axis=1)    = [2 1 0]


In [14]:
np.argmax(z2, axis = 1)

array([4, 4], dtype=int64)

### **轉置 Array** (轉置矩陣)
- 透過呼叫 Numpy Array 的 `.T` 屬性來取得轉置矩陣

In [15]:
z2.T        # 轉置矩陣

array([[0, 5],
       [1, 6],
       [2, 7],
       [3, 8],
       [4, 9]])

### **Array 的乘法**
- 使用 `*` 運算子來進行**元素**層級的乘法。
- 使用 `.dot()` method 來進行一維或二維矩陣的**內積**。
- 使用 `matmul()` function 來進行**矩陣乘法**。

#### **元素相乘 (a*b)**

In [16]:
a = z2[0, :]    # 取 z2 的第一個維度的第 0 組資料
b = z2[1, :]    # 取 z2 的第一個維度的第 1 組資料

# 查看 a 的形狀
print(a)
print('{:<20}'.format('data shape (a):'), end='')
print(a.shape)

# 查看 b 的情況
print('-------------------------------')
print(b)
print('{:<20}'.format('data shape (b):'), end='')
print(b.shape)

# 查看 a*b 的情況 (a 與 b 的元素相乘)
print('-------------------------------')
print(a * b)
print('{:<20}'.format('data shape (a*b):'), end='')
print((a*b).shape)

[0 1 2 3 4]
data shape (a):     (5,)
-------------------------------
[5 6 7 8 9]
data shape (b):     (5,)
-------------------------------
[ 0  6 14 24 36]
data shape (a*b):   (5,)


#### **一維矩陣 (向量) 的內積 (a.dot(b))**

In [17]:
# 一維數組的內積
vector1 = np.array([1, 2, 3])
vector2 = np.array([4, 5, 6])
result = np.dot(vector1, vector2)  # 結果是 1*4 + 2*5 + 3*6 = 32

# 查看 result 的情況 (vector1 與 vector2 內積)
print(result)

print('-------------------------------')
print('{:<20}'.format('data type (result):'), end='')   # 轉為純量
print(type(result))

print('-------------------------------')
print('{:<20}'.format('data shape (result):'), end='')
print((result).shape)

32
-------------------------------
data type (result): <class 'numpy.int32'>
-------------------------------
data shape (result):()


#### **二維矩陣的內積 (a.dot(b))**

In [18]:
# 二維矩陣的乘法
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])
result2 = np.dot(matrix1, matrix2)

# 查看 result 的情況 (matrix1 與 matrix2 內積)
# 結果是一個新的矩陣:
# [[1*5 + 2*7, 1*6 + 2*8],
#  [3*5 + 4*7, 3*6 + 4*8]]
print(result2)

print('-------------------------------')
print('{:<23}'.format('data type (result2):'), end='')   # 轉為純量
print(type(result2))

print('-------------------------------')
print('{:<23}'.format('data shape (result2):'), end='')
print((result2).shape)

[[19 22]
 [43 50]]
-------------------------------
data type (result2):   <class 'numpy.ndarray'>
-------------------------------
data shape (result2):  (2, 2)


#### **兩個矩陣的乘法 (matmul(a, b))**

In [19]:
np.matmul(z2, z2.T)

array([[ 30,  80],
       [ 80, 255]])

#### **對 Array 進行 size 的調整** (對所有元素做倍率調整)
- 使用 `power(array_name, constant)` 來達成 (其實一樣可以做兩個矩陣的乘法，詳情[見此](https://numpy.org/doc/stable/reference/generated/numpy.power.html))

In [20]:
np.power(z2, 0.5)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ]])

- 使用 `sqrt(array_name)` function 也可以達到與 `power(array_name, 0.5)` 一樣效果

### **lambda 表達式**
- 使用一行程式碼來定義函數

語法比較：
- 傳統函式定義方法：
```python
    def 函數名稱(要放入的變數):
        要做的計算
        return 要返回的變數
```
- lambda 表達式的函式定義方法
```python
    函數名稱 = lambda 要放入的變數: 要返回的變數需要做的計算
```

In [21]:
def plus_trad(x, y):
    result = x + y
    return result

plus_lambda = lambda x, y: x + y

print(plus_trad(91, 153))
print(plus_lambda(91, 153))

244
244
